digraph G{
	rankdir = LR;
	//IA,TOPICOS,GESTION,SEGURIDAD,MERCA[style=filled,color=".7 .3 1.0"];
	//8vo ciclo
	GESTION -> TESIS1;
	GESTION -> DYEP;
	MERCA -> PLANEAMIENTO;
	//9no ciclo
	TOPICOS -> ANE;
	TESIS1 -> TESIS2;
	SEGURIDAD -> AUDITORIA;
	DYEP -> GPI;
	PLANEAMIENTO -> IE;
	//ELECTIVOS
	IDEOLOGIAS -> REALIDAD;
	DISEÑOGRAFICO -> TALLERHERRAMIENTASRV;
	COMPORTAMIENTO -> ADMRH;
	IA -> IAAVANZADA;
	GESTION -> BOLSA;
	GESTION -> FINANCIAMIENTO;
	GESTION -> DIAGNOSTICO;
	GESTION -> GESTIONNEG1;
	MERCA -> COMERCIO;
	AUTOMATIZACION -> ROBOTICA;

	//8vo ciclo
	{ rank = same; IA GESTION MERCA }
	//9no ciclo
	{ rank = same; TOPICOS TESIS1 SEGURIDAD DYEP PLANEAMIENTO }
	//10mo ciclo
	{ rank = same; ANE TESIS2 AUDITORIA GPI IE }
	//electivos
	{ IDEOLOGIAS,REALIDAD,LITERATURA,DISEÑOGRAFICO,TALLERHERRAMIENTAS1,COMPORTAMIENTO,ANALISISECONOMICO,TDA,TALLERHERRAMIENTASRV,ADMRH,SISTCOSTOS,MODELOSGE,IAAVANZADA,AUTOMATIZACION,BOLSA,FINANCIAMIENTO,DIAGNOSTICO,GESTIONNEG1,TOPICOSNEG,COMERCIO,ROBOTICA[style=filled,color=".7 .3 1.0"] }
}


