digraph G{
	//IA,TOPICOS,GESTION,SEGURIDAD,MERCA[style=filled,color=".7 .3 1.0"];
	//1er Ciclo

	//ELECTIVOS

	DISEÑOGRAFICO -> TALLERHERRAMIENTASRV;
	COMPORTAMIENTO -> ADMRH;

	IA -> IAAVANZADA;
	AUTOMATIZACION -> ROBOTICA;
	
	//8vo ciclo
	{ rank = same; IA }
	//10mo ciclo
	{ rank = same; ANE TESIS2 AUDITORIA GPI IE }
	//electivos
	{ IDEOLOGIAS,REALIDAD,LITERATURA,PROTOCOLO,DISEÑOGRAFICO,TALLERHERRAMIENTAS1,COMPORTAMIENTO,SISTECONOMICOS,ANALISISECONOMICO,TALLERHERRAMIENTASRV,SISTHUMANOS,ADMRH,TALLER2,KM,TLENG,SISTCOSTOS,MODELOSGE,IAAVANZADA,INGSOFTAVANZ,AUTOMATIZACION,SERVCD,BOLSA,FINANCIAMIENTO,GESTIONNEG1,TOPICOSNEG,COMERCIO,ROBOTICA[style=filled,color=".7 .3 1.0"] }
}


