digraph G{
	node[shape=box];
	rankdir = LR;
	APLICADA,MATEAPLICADA,MODERNA,OYM,MACRO,IO1,ELECTRICOS,CONTA,DINAMICA,AYD[style=filled,color=".7 .3 1.0"];
	//4to ciclo

	//5to ciclo
	IO1 -> PRODUCTIVOS;
	IO1 -> IO2;
	ELECTRICOS -> DIGITALES;
	MODERNA -> DIGITALES;
	OYM -> CREATIVIDAD;
	//6to ciclo
	DINAMICA -> SIMULACION;
	AYD -> ABD;
	AYD -> TALLER;
	PRODUCTIVOS -> LOGISTICA;
	DIGITALES -> ARQUI;
	DIGITALES -> OPERATIVOS;
	CONTA -> COSTOS;

	//4to ciclo
	{ rank = source; LPOO NUMERICO ECUA MICRO APLICADA FISICA2 }
	//5to ciclo
	{ rank = same; MODELAMIENTO MATEAPLICADA IO1 ELECTRICOS MODERNA MACRO OYM }
	//6to ciclo
	{ rank = same; DINAMICA AYD PRODUCTIVOS IO2 DIGITALES CONTA }
	//7mo ciclo
	{ rank = same; SIMULACION ABD TALLER ARQUI OPERATIVOS COSTOS CREATIVIDAD }
}
