#include<bits/stdc++.h>
using namespace std;

#define sc( x ) scanf( "%d" , &x )
#define REP( i , n ) for( int  i = 0 ; i < (n) ; ++i )
#define clr( t , val ) memset( t , val , sizeof( t ) )

#define pb push_back
#define all( v ) v.begin() , v.end()
#define SZ( v ) ((int)(v).size())

#define mp make_pair
#define fi first
#define se second

#define DEBUG( x ) cout << #x << " " << (x) << endl;

#define N 1000

typedef vector< int > vi;
typedef vector< vi > vvi;
typedef long long ll;

bool f( int x , int E, int EM, int M, int MH, int H ){
	vi v( 3 , x );
	v[ 0 ] -= min( v[ 0 ] , E );
	v[ 1 ] -= min( v[ 1 ] , M );
	v[ 2 ] -= min( v[ 2 ] , H );
	
	int cur;
	cur = min( v[ 0 ] , EM );
	v[ 0 ] -= cur;
	EM -= cur;
	
	cur = min( v[ 1 ] , EM );
	v[ 1 ] -= cur;
	EM -= cur;
	
	cur = min( v[ 1 ] , MH );
	v[ 1 ] -= cur;
	MH -= cur;
	
	cur = min( v[ 2 ] , MH );
	v[ 2 ] -= cur;
	MH -= cur;
	
	return v == vi( 3 , 0 );
}
class ProblemSetsEasy {
public:
	int maxSets(int E, int EM, int M, int MH, int H) {
		int lo = 0 , hi = 1000000 + 5;
		while( hi - lo > 1 ){
			int med = (lo + hi) >>1;
			if( f( med , E , EM , M , MH , H ) ) lo = med;
			else hi = med;
		}
		return lo;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, int p0, int p1, int p2, int p3, int p4, bool hasAnswer, int p5) {
	cout << "Test " << testNum << ": [" << p0 << "," << p1 << "," << p2 << "," << p3 << "," << p4;
	cout << "]" << endl;
	ProblemSetsEasy *obj;
	int answer;
	obj = new ProblemSetsEasy();
	clock_t startTime = clock();
	answer = obj->maxSets(p0, p1, p2, p3, p4);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p5 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p5;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	int p0;
	int p1;
	int p2;
	int p3;
	int p4;
	int p5;
	
	{
	// ----- test 0 -----
	p0 = 2;
	p1 = 2;
	p2 = 1;
	p3 = 2;
	p4 = 2;
	p5 = 3;
	all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, p4, true, p5) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	p0 = 100;
	p1 = 100;
	p2 = 100;
	p3 = 0;
	p4 = 0;
	p5 = 0;
	all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, p4, true, p5) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	p0 = 657;
	p1 = 657;
	p2 = 657;
	p3 = 657;
	p4 = 657;
	p5 = 1095;
	all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, p4, true, p5) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	p0 = 1;
	p1 = 2;
	p2 = 3;
	p3 = 4;
	p4 = 5;
	p5 = 3;
	all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, p4, true, p5) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	p0 = 100000;
	p1 = 100000;
	p2 = 100000;
	p3 = 100000;
	p4 = 100000;
	p5 = 166666;
	all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, p4, true, p5) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
